"""Marker-guarded export apply for `anvil:project-share` (issue #396).

Executes a :class:`~.plan.SharePlan`:

1. **Marker guard**: the out dir is rebuilt (deleted + recreated) only
   when it is absent, empty, or carries the ``EXPORT.md`` marker from a
   previous run. A non-empty out dir WITHOUT the marker is a hard
   refusal — no deletion, no partial write (AC 6).
2. **Copy**: every planned file (``shutil.copy2``, parents created on
   demand). Wholesale copy of the resolved version dir's contents minus
   the strip list — PDFs, figures/, exhibits/, speaker-notes ride along
   without per-skill special-casing.
3. **EXPORT.md**: recipient-facing provenance index (project name, UTC
   build timestamp, ordering source, per-doc resolved version + mode +
   PDF SHA-256, findings for failed docs). Doubles as the rebuild
   marker.
4. **``--zip``** (optional): ``<project>/<dirname>-share-YYYYMMDD.zip``
   of the out tree via stdlib ``shutil.make_archive`` — no new Python
   dep (subprocess-only / stdlib contract preserved).
5. **Gitignore suggestion**: when the out dir is not covered by the
   consumer's ``.gitignore``, a one-line suggestion is recorded on the
   result. The skill does NOT auto-edit consumer files on a routine
   command (the installer's one-time CLAUDE.md append is not a
   precedent for per-run edits).
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from .citations import CitationLintResult
from .plan import (
    MARKER_FILENAME,
    ORDERING_EXPORT_ORDER,
    OUT_FOREIGN,
    SharePlan,
    inspect_out_dir,
)


@dataclass
class ApplyResult:
    """Outcome of :func:`apply_plan`."""

    out_dir: Path
    refused: bool = False
    refusal_reason: Optional[str] = None
    files_copied: int = 0
    export_md: Optional[Path] = None
    zip_path: Optional[Path] = None
    gitignore_note: Optional[str] = None
    failed_doc_slugs: List[str] = field(default_factory=list)


def _utc(now: Optional[datetime]) -> datetime:
    if now is None:
        return datetime.now(timezone.utc)
    if now.tzinfo is None:
        return now.replace(tzinfo=timezone.utc)
    return now.astimezone(timezone.utc)


def render_export_md(
    plan: SharePlan,
    now: datetime,
    *,
    citations: Optional[CitationLintResult] = None,
) -> str:
    """Render the recipient-facing EXPORT.md index (the rebuild marker).

    ``citations`` (issue #758): when the dangling-citation lint found
    anything, it's noted here — report only, since the citation may be
    deliberate (e.g. an internal cross-reference the recipient isn't
    meant to follow).
    """
    lines: List[str] = []
    lines.append(f"# Share export: {plan.project_name}")
    lines.append("")
    lines.append(
        "<!-- Generated by anvil:project-share. This file is the rebuild "
        "marker: re-exporting deletes and rebuilds this directory only "
        "when this file is present. -->"
    )
    lines.append("")
    lines.append(f"**Project**: {plan.project_name}")
    lines.append(f"**Built**: {now.strftime('%Y-%m-%dT%H:%M:%SZ')}")
    ordering = (
        "`export.order` (BRIEF override)"
        if plan.ordering_source == ORDERING_EXPORT_ORDER
        else "`documents:` (BRIEF default)"
    )
    lines.append(f"**Ordering**: {ordering}")
    lines.append(f"**Documents**: {len(plan.docs)}")
    lines.append("")
    lines.append("| # | Document | Version | Resolution | PDF | SHA-256 |")
    lines.append("|---|----------|---------|------------|-----|---------|")
    for doc in plan.docs:
        if doc.failed:
            lines.append(
                f"| {doc.ordinal:02d} | `{doc.slug}` | — | FAILED | — | — |"
            )
            continue
        c = doc.collection
        if c.pdfs:
            for i, pdf in enumerate(c.pdfs):
                ordinal = f"{doc.ordinal:02d}" if i == 0 else ""
                slug = f"`{doc.slug}`" if i == 0 else ""
                version = f"`{c.resolved_name}`" if i == 0 else ""
                mode = c.resolution_mode if i == 0 else ""
                lines.append(
                    f"| {ordinal} | {slug} | {version} | {mode} | "
                    f"`{pdf.filename}` | `{pdf.sha256}` |"
                )
        else:
            lines.append(
                f"| {doc.ordinal:02d} | `{doc.slug}` | `{c.resolved_name}` "
                f"| {c.resolution_mode} | (no rendered PDF) | — |"
            )
    lines.append("")

    if plan.research_files:
        lines.append(
            f"Shared research pool: `research/` "
            f"({len(plan.research_files)} files)."
        )
        lines.append("")

    if plan.excluded_slugs:
        lines.append("## Excluded")
        lines.append("")
        for slug in plan.excluded_slugs:
            lines.append(
                f"- `{slug}`: listed in BRIEF.documents but omitted from "
                f"`export.order`."
            )
        lines.append("")

    failed = plan.failed_docs
    if failed:
        lines.append("## Findings")
        lines.append("")
        for doc in failed:
            lines.append(f"- `{doc.slug}`: {doc.failure}")
        lines.append("")

    if citations is not None and citations.findings:
        lines.append("## Citations")
        lines.append("")
        lines.append(
            f"{len(citations.findings)} possible dangling citation(s) "
            f"found (report only — may be deliberate):"
        )
        lines.append("")
        for f in citations.findings:
            lines.append(
                f"- `{f.source_rel}` cites `{f.citation_text}` -> "
                f"`{f.resolved_rel}`, which is not part of this export"
            )
        lines.append("")

    return "\n".join(lines) + "\n"


def _gitignore_covers(line: str, out_name: str) -> bool:
    """Heuristic: does one .gitignore line cover the out dir name?"""
    candidates = {
        out_name,
        f"{out_name}/",
        f"/{out_name}",
        f"/{out_name}/",
        f"**/{out_name}",
        f"**/{out_name}/",
    }
    return line in candidates or line.endswith(f"/{out_name}") or line.endswith(
        f"/{out_name}/"
    )


def gitignore_suggestion(project_dir: Path, out_name: str) -> Optional[str]:
    """One-line suggestion when the out dir isn't gitignored.

    Walks up from ``project_dir`` to the enclosing git root (a dir
    carrying ``.git``), checking every ``.gitignore`` on the way. When
    no enclosing git repo exists, returns ``None`` (nothing to
    suggest). Never edits any file.
    """
    project_dir = Path(project_dir).resolve()
    current = project_dir
    in_repo = False
    for _ in range(64):
        gitignore = current / ".gitignore"
        if gitignore.is_file():
            try:
                for raw in gitignore.read_text(encoding="utf-8").splitlines():
                    line = raw.strip()
                    if not line or line.startswith("#"):
                        continue
                    if _gitignore_covers(line, out_name):
                        return None
            except OSError:
                pass
        if (current / ".git").exists():
            in_repo = True
            break
        if current.parent == current:
            break
        current = current.parent
    if not in_repo:
        return None
    return (
        f"`{out_name}/` is a build artifact and is not covered by your "
        f".gitignore — consider adding `{out_name}/` to it."
    )


def apply_plan(
    plan: SharePlan,
    *,
    zip_output: bool = False,
    now: Optional[datetime] = None,
    citations: Optional[CitationLintResult] = None,
) -> ApplyResult:
    """Execute the plan: marker-guarded rebuild, copies, EXPORT.md, zip.

    Per-doc resolution failures recorded on the plan do NOT abort the
    apply — the resolvable docs still export and the findings land in
    EXPORT.md (AC 9). Only the marker-guard refusal prevents writing.

    ``citations``: the dangling-citation lint outcome (issue #758),
    when the caller already computed one against this same plan. Noted
    in EXPORT.md; never blocks the write.
    """
    now = _utc(now)
    out_dir = plan.out_dir
    result = ApplyResult(out_dir=out_dir)
    result.failed_doc_slugs = [d.slug for d in plan.failed_docs]

    state = inspect_out_dir(out_dir)
    if state == OUT_FOREIGN:
        result.refused = True
        result.refusal_reason = (
            f"Refusing to rebuild {out_dir}: the directory is non-empty "
            f"and does not carry the `{MARKER_FILENAME}` marker from a "
            f"previous export. It may not be ours to delete. Suggested "
            f"fix: move or remove the directory, or point `export.out` "
            f"at a dedicated name."
        )
        return result

    # Blow away & rebuild: the out dir is a disposable build artifact,
    # not source-of-truth. Stale files from removed/renamed docs
    # disappear by construction.
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    for fp in plan.all_file_plans:
        target = out_dir / fp.target_rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(fp.source, target)
        result.files_copied += 1

    export_md = out_dir / MARKER_FILENAME
    export_md.write_text(
        render_export_md(plan, now, citations=citations), encoding="utf-8"
    )
    result.export_md = export_md

    if zip_output:
        base_name = (
            plan.project_dir
            / f"{plan.project_dir.name}-share-{now.strftime('%Y%m%d')}"
        )
        archive = shutil.make_archive(
            str(base_name),
            "zip",
            root_dir=str(plan.project_dir),
            base_dir=plan.config.out,
        )
        result.zip_path = Path(archive)

    result.gitignore_note = gitignore_suggestion(
        plan.project_dir, plan.config.out
    )
    return result


__all__ = [
    "ApplyResult",
    "apply_plan",
    "gitignore_suggestion",
    "render_export_md",
]
